FROM pytorch/pytorch:latest
COPY ./requirements.txt /nmt_service/
RUN apt update
RUN apt install -y build-essential
RUN pip install --upgrade pip
RUN pip install Cython
RUN pip install -r /nmt_service/requirements.txt
RUN pip install python-telegram-bot
COPY . /nmt_service
WORKDIR /nmt_service/
#CMD ["python", "/nmt_service/test.py"]